-pj ksb -si cpm5n_ipp_v5_0 -rc cpm5n -ep cpm5n --cpm_mode c0c1          --lane_count x4 --processor a72 -b haps-4  -s 0
-pj ksb -si cpm5n_ipp_v5_0 -rc cpm5n -ep cpm5n --cpm_mode c2c3          --lane_count x4 --processor a72 -b haps-4  -s 2
