# contains possible choices for run_burst user argument
options = {
    "silicon_revision": [
        "da7_prod",
        "da7_es2",
        "remus",
        "prod",
        "ps_ddr_12_0",
        "ps_me_12_0",
        "ps_me_es2_4_1",
        "ps_me_es2_5_0",
        "es1",
        "es2",
        "es1_ps",
        "es1_me",
        "es1_pscon4",
        "es2_cpmrc",
        "es2_cpmep",
        "ps_ddr_es2_5_0",
        "ps_ddr_es2_4_1",
        "ps_me_es2_4_2",
        "ps_ddr_es2_4_2",
        "h20_ipp_4_0",
        "h20_ipp_es1_TO",
        "h20_ipp_es2_v2_0",
        "aie2_vdu_ipp_5_0",
        "es2_ps",
        "es2_pscon4",
        "es2_me",
        "jamling_es1",
        "h10_cpm5_es1_6_0",
        "h10_cpm5_es2_1_0",
        "h10_es1_ps",
        "h10_es1_cpmep",
        "h10_es1_cpmrc",
        "h10_es2_cpmrc",
        "h10_es2_cpmep",
        "psxl_spp_v4_0_ddr5",
        "psxl_spp_v5_0_ddr5",
        "cpm5n_ipp_v2_2",
        "cpm5n_ipp_v3_0",
        "cpm5n_ipp_v4_0",
        "cpm5n_ipp_v5_0",
    ],
    "daughter_card": [
        "dc1",
        "dc2",
        "se1",
        "se2",
        "se3",
        "se4",
        "se5",
        "se6",
        "se7",
        "se8",
    ],
    "board_revision": ["rev1.0", "rev1.1", "revb", "revc", "revd", ""],
    "root_complex": [
        "alto",
        "x86",
        "k7",
        "remus",
        "v7",
        "s80",
        "cpm5",
        "h10",
        "cpm5n",
    ],
    "end_point": [
        "alto",
        "k7",
        "v7",
        "s80",
        "s80v350",
        "cpm5",
        "h10",
        "vpk120",
        "cpm5n",
    ],
    "lane_count": ["x1", "x4", "x8", "x16"],
    "pcie_gen": ["g1", "g2", "g3", "g4", "g5"],
    "bridge_rc": ["axipcie", "nwlpcie", "plb2pcie", "xdmapcie"],
    "bridge_ep": ["axipcie", "nwlpcie", "plb2pcie", "xdmapcie"],
    "cpm_mode": [
        "qdma",
        "a1",
        "xdma",
        "a0cci",
        "a0noc",
        "ccix",
        "plst",
        "aximm0",
        "aximm1",
        "aximmc0",
        "aximmc1",
        "psccix",
        "epcxs",
        "rccxs",
        "epchi1",
        "epchi1opttlp",
        "c0c1epegress",
        "c0c1rcegress",
        "c2c3epegress",
        "c2c3rcegress",
        "c0c1epegressqdma",
        "c2c3epegressqdma",
        "c0c1",
        "c1c0",
        "c2c3",
        "c3c2",
        "c0c1qdma",
        "c2c3qdma",
    ],
    "ddr_mode": ["sddr", "dddr", "lpddr", "sddrd2", "3ddr", "qddr"],
    "config_rc": ["cfg0", "cfg4"],
    "project": [
        "pele_manual",
        "pele",
        "alto",
        "everest",
        "ksb",
        "everest_manual",
        "virtex7",
        "kintex7",
    ],
    "processor": ["a9", "a53", "r5", "mb", "x86", "a72", "a78", "r52", "r52-lockstep"],
    "clock": ["av", "sivdef"],
    "tile": ["1x1", "3x3"],
}

# Differences in BUSG and systest naming
# Note: edit systest_cmd_create function if required
systest_map = {
    "da7_prod": "da7-prod",
    "da7_es2": "da7-es2",
    "rev1.0": "patched-rev1.0",
    "rev1.1": "B-rev1.1",
    "revb": "B-revB,patched-rev1.0",
    "revc": "B-revC",
    "revd": "B-revD,patched-rev1.0",
    "remus": "",
    "prod": "",
}

pre_silicon_boards = ["protium", "palladium", "ep108", "ep107", "haps"]

empty_si_board_list = ["zc165x", "palladium", "haps", "tenzing", "tenpro", "xa2785", "vck190", "ph1760"]


pci_cluster_dictionary = {
        "alto_rc_alto_ep": "pcie_zcu102",
        "alto_rc_k7_ep": "pcie_zcu102",
        "cpm5_rc_cpm5_ep": "protium",
        "s80_rc_s80v350_ep": "pcie_cpm",
        "s80_rc_k7_ep": "pcie_cpm",
        "h10_rc_h10_ep": "pcie_xa2785",
        "h10_rc_vpk120_ep": "pcie_xa2785",
        "h10_rc_s80v350_ep": "pcie_xa2785",
        "h10_rc_k7_ep": "pcie_xa2785",
        "k7_rc_alto_ep": "pcie705",
        "k7_rc_k7_ep": "pcie705",
        "v7_rc_v7_ep": "pcie707",
        "x86_rc_alto_ep": "pcie_x86",
        "x86_rc_s80v350_ep": "pcie_x86",
        "x86_rc_h10_ep": "pcie_x86",
        "x86_rc_vpk120_ep": "pcie_x86",
        "cpm5n_rc_cpm5n_ep": "haps",
        "x86_rc_k7_ep": "pcie_x86"
    }

pci_ep_map = {
    "alto_ep" : "ep-zcu112",
    "k7_ep" : "ep-kc705",
    "v7_ep" : "ep-vc707",
    "s80_ep" : "ep-ten",
    "s80v350_ep" : "ep-v350",
    "h10_ep": "ep-xa2785",
    "vpk120_ep": "ep-vpk120",
    "cpm5_ep" : "",
    "cpm5n_ep" : ""
}

pci_rc_map = {
    "k7_rc" : "rc-kc705",
    "v7_rc" : "rc-vc707",
    "h10_rc": "rc-xa2785",
    "x86_rc": "",
    "alto_rc" : "rc-zcu102",
    "s80_rc": "rc-ten",
    "cpm5_rc" : "SPP_PS_ME_CPM",
    "cpm5n_rc" : "cpm5n"
}
